use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

#[derive(Clone)]
struct ScriptRange {
    start: String,
    end: String,
    alias: String,
    name: Option<String>,
}

pub fn ensure_generated_unicode_lisp(manifest_dir: &Path, project_root: &Path) {
    let data_dir = manifest_dir.join("unicode-data");
    let out_dir = project_root.join("lisp").join("international");

    let blocks = data_dir.join("Blocks.txt");
    let emoji_data = data_dir.join("emoji-data.txt");
    let emoji_zwj_sequences = data_dir.join("emoji-zwj-sequences.txt");
    let emoji_sequences = data_dir.join("emoji-sequences.txt");

    for path in [&blocks, &emoji_data, &emoji_zwj_sequences, &emoji_sequences] {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    if !(blocks.exists()
        && emoji_data.exists()
        && emoji_zwj_sequences.exists()
        && emoji_sequences.exists())
    {
        return;
    }

    let charscript = generate_charscript(&blocks, &emoji_data);
    let emoji_zwj = generate_emoji_zwj(&emoji_zwj_sequences, &emoji_sequences);

    write_if_changed(&out_dir.join("charscript.el"), &charscript);
    write_if_changed(&out_dir.join("emoji-zwj.el"), &emoji_zwj);
}

fn write_if_changed(path: &Path, content: &str) {
    let current = fs::read_to_string(path).ok();
    if current.as_deref() == Some(content) {
        return;
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create unicode lisp output directory");
    }
    fs::write(path, content).unwrap_or_else(|err| panic!("write {}: {err}", path.display()));
}

fn generate_charscript(blocks: &Path, emoji_data: &Path) -> String {
    let mut ranges = Vec::new();

    for line in fs::read_to_string(blocks)
        .unwrap_or_else(|err| panic!("read {}: {err}", blocks.display()))
        .lines()
    {
        if !starts_with_hex(line) {
            continue;
        }
        let Some((range, name)) = line.split_once(';') else {
            continue;
        };
        let range = range.trim();
        let name = name.trim();
        let Some((mut start, end)) = range.split_once("..") else {
            continue;
        };
        if start == "0080" {
            start = "00A0";
        }

        if start == "3300" {
            push_fixed_range(
                &mut ranges,
                "3300".to_string(),
                "3357".to_string(),
                "kana".to_string(),
                Some("Katakana".to_string()),
            );
            push_block_range(
                &mut ranges,
                "3358".to_string(),
                "33FF".to_string(),
                Some("CJK Compatibility".to_string()),
            );
            continue;
        }

        push_block_range(
            &mut ranges,
            start.to_string(),
            end.to_string(),
            Some(name.to_string()),
        );
    }

    for line in fs::read_to_string(emoji_data)
        .unwrap_or_else(|err| panic!("read {}: {err}", emoji_data.display()))
        .lines()
    {
        if !starts_with_hex(line) || !line.contains("; Emoji_Presentation ") {
            continue;
        }
        let Some((range, _rest)) = line.split_once(';') else {
            continue;
        };
        let range = range.trim();
        let (start, end) = match range.split_once("..") {
            Some((start, end)) => (start.to_string(), end.to_string()),
            None => (range.to_string(), range.to_string()),
        };
        ranges.push(ScriptRange {
            start,
            end,
            alias: "emoji".to_string(),
            name: Some("Autogenerated emoji".to_string()),
        });
    }

    ranges.push(ScriptRange {
        start: "FE0F".to_string(),
        end: "FE0F".to_string(),
        alias: "emoji".to_string(),
        name: Some("Autogenerated emoji (override)".to_string()),
    });

    let mut out = String::new();
    out.push_str(";;; charscript.el --- character script table  -*- lexical-binding:t -*-\n");
    out.push_str(";;; Automatically generated from admin/unidata/{Blocks,emoji-data}.txt\n");
    out.push_str("(let (script-list)\n");
    out.push_str("  (dolist (elt '(\n");
    for entry in &ranges {
        let _ = write!(
            out,
            "    (#x{} #x{} {})",
            entry.start, entry.end, entry.alias
        );
        if let Some(name) = &entry.name {
            if !entry.alias.contains('-') && entry.alias != name.to_ascii_lowercase() {
                let _ = write!(out, " ; {name}");
            }
        }
        out.push('\n');
    }
    out.push_str("    ))\n");
    out.push_str("    (set-char-table-range char-script-table\n");
    out.push_str("\t\t\t  (cons (car elt) (nth 1 elt)) (nth 2 elt))\n");
    out.push_str("    (or (memq (nth 2 elt) script-list)\n");
    out.push_str("\t(setq script-list (cons (nth 2 elt) script-list))))\n");
    out.push_str("  (set-char-table-extra-slot char-script-table 0 (nreverse script-list)))\n");
    out.push('\n');
    out.push_str("(map-char-table\n");
    out.push_str(" (lambda (ch script)\n");
    out.push_str("   (and (eq script 'symbol)\n");
    out.push_str("\t(modify-category-entry ch ?5)))\n");
    out.push_str(" char-script-table)\n");
    out.push('\n');
    out.push_str("(provide 'charscript)\n");
    out
}

fn push_fixed_range(
    ranges: &mut Vec<ScriptRange>,
    start: String,
    end: String,
    alias: String,
    name: Option<String>,
) {
    ranges.push(ScriptRange {
        start,
        end,
        alias,
        name,
    });
}

fn push_block_range(
    ranges: &mut Vec<ScriptRange>,
    start: String,
    end: String,
    name: Option<String>,
) {
    let Some(name) = name else {
        return;
    };
    let Some(alias) = name_to_alias(&name) else {
        return;
    };

    if let Some(last) = ranges.last_mut() {
        if last.alias == alias && parse_hex(&start) == parse_hex(&last.end).saturating_add(1) {
            last.end = end;
            last.name = Some(match last.name.take() {
                Some(prev) => format!("{prev}, {name}"),
                None => name,
            });
            return;
        }
    }

    ranges.push(ScriptRange {
        start: start.clone(),
        end,
        alias: alias.clone(),
        name: Some(name),
    });

    match start.as_str() {
        "0370" => {
            if let Some(last) = ranges.last_mut() {
                last.end = "03E1".to_string();
            }
            ranges.push(ScriptRange {
                start: "03E2".to_string(),
                end: "03EF".to_string(),
                alias: "coptic".to_string(),
                name: None,
            });
            ranges.push(ScriptRange {
                start: "03F0".to_string(),
                end: "03FF".to_string(),
                alias: "greek".to_string(),
                name: None,
            });
        }
        "FB00" => {
            if let Some(last) = ranges.last_mut() {
                last.end = "FB06".to_string();
            }
            ranges.push(ScriptRange {
                start: "FB13".to_string(),
                end: "FB17".to_string(),
                alias: "armenian".to_string(),
                name: None,
            });
            ranges.push(ScriptRange {
                start: "FB1D".to_string(),
                end: "FB4F".to_string(),
                alias: "hebrew".to_string(),
                name: None,
            });
        }
        "FF00" => {
            if let Some(last) = ranges.last_mut() {
                last.end = "FF60".to_string();
            }
            ranges.push(ScriptRange {
                start: "FF61".to_string(),
                end: "FF9F".to_string(),
                alias: "kana".to_string(),
                name: None,
            });
            ranges.push(ScriptRange {
                start: "FFA0".to_string(),
                end: "FFDF".to_string(),
                alias: "hangul".to_string(),
                name: None,
            });
            ranges.push(ScriptRange {
                start: "FFE0".to_string(),
                end: "FFEF".to_string(),
                alias: "cjk-misc".to_string(),
                name: None,
            });
        }
        _ => {}
    }
}

fn name_to_alias(name: &str) -> Option<String> {
    let lower = name.to_ascii_lowercase();

    let direct = direct_aliases();
    if let Some(alias) = direct.get(lower.as_str()) {
        return Some((*alias).to_string());
    }

    if lower.contains("for symbols") {
        return Some("symbol".to_string());
    }
    if lower.contains("latin")
        || (lower.contains("combining") && lower.contains("marks"))
        || lower.contains("spacing modifier")
        || lower.contains("tone letters")
        || lower.contains("alphabetic presentation")
    {
        return Some("latin".to_string());
    }
    if lower.contains("cjk") || lower.contains("enclosed ideograph") || lower.contains("kangxi") {
        return Some("han".to_string());
    }
    if lower.contains("arabic") {
        return Some("arabic".to_string());
    }
    if lower.starts_with("greek") {
        return Some("greek".to_string());
    }
    if lower.starts_with("coptic") {
        return Some("coptic".to_string());
    }
    if lower.contains("cuneiform number") || lower.contains("cuneiform") {
        return Some("cuneiform".to_string());
    }
    if lower.contains("mathematical alphanumeric symbol") {
        return Some("mathematical".to_string());
    }
    if contains_any(
        &lower,
        &[
            "punctuation",
            "mathematical",
            "arrows",
            "currency",
            "superscript",
            "small form variants",
            "geometric",
            "dingbats",
            "enclosed",
            "alchemical",
            "pictograph",
            "emoticon",
            "transport",
        ],
    ) {
        return Some("symbol".to_string());
    }
    if lower.contains("canadian aboriginal") {
        return Some("canadian-aboriginal".to_string());
    }
    if lower.contains("katakana") || lower.contains("hiragana") {
        return Some("kana".to_string());
    }
    if lower.contains("myanmar") {
        return Some("burmese".to_string());
    }
    if lower.contains("hangul") {
        return Some("hangul".to_string());
    }
    if lower.contains("khmer") {
        return Some("khmer".to_string());
    }
    if lower.contains("braille") {
        return Some("braille".to_string());
    }
    if lower.starts_with("yi ") {
        return Some("yi".to_string());
    }
    if contains_any(
        &lower,
        &["surrogates", "private use", "variation selectors"],
    ) {
        return None;
    }
    if lower == "specials" || lower == "tags" {
        return None;
    }
    if lower.contains("linear b") {
        return Some("linear-b".to_string());
    }
    if lower.contains("aramaic") {
        return Some("aramaic".to_string());
    }
    if lower.contains("rumi num") {
        return Some("arabic".to_string());
    }
    if lower.contains("duployan") || lower.contains("shorthand") {
        return Some("duployan-shorthand".to_string());
    }
    if lower.contains("sutton signwriting") {
        return Some("sutton-sign-writing".to_string());
    }
    if lower.contains("sinhala archaic number") {
        return Some("sinhala".to_string());
    }
    if lower.contains("tangut components") {
        return Some("tangut".to_string());
    }

    let mut transformed = lower;
    if transformed.starts_with("small ") {
        transformed = transformed.trim_start_matches("small ").to_string();
    }

    if let Some(idx) = earliest_match(
        &transformed,
        &[" extended", " extensions", " extension", " supplement"],
    ) {
        transformed.truncate(idx);
    }

    transformed = transformed.replacen("numbers", "number", 1);
    transformed = transformed.replacen("numerals", "numeral", 1);
    transformed = transformed.replacen("symbols", "symbol", 1);
    if let Some(stripped) = transformed.strip_suffix("forms") {
        transformed = format!("{stripped}form");
    }
    if let Some(stripped) = transformed.strip_suffix("tiles") {
        transformed = format!("{stripped}tile");
    }
    if transformed.starts_with("new ") {
        transformed = transformed.trim_start_matches("new ").to_string();
    }
    for suffix in [
        " characters",
        " hieroglyphs",
        " cursive",
        " hieroglyph format controls",
    ] {
        if let Some(stripped) = transformed.strip_suffix(suffix) {
            transformed = stripped.to_string();
            break;
        }
    }
    transformed = transformed.replace(' ', "-");
    Some(transformed)
}

fn direct_aliases() -> HashMap<&'static str, &'static str> {
    HashMap::from([
        ("ipa extensions", "phonetic"),
        ("letterlike symbols", "symbol"),
        ("number forms", "symbol"),
        ("miscellaneous technical", "symbol"),
        ("control pictures", "symbol"),
        ("optical character recognition", "symbol"),
        ("enclosed alphanumerics", "symbol"),
        ("box drawing", "symbol"),
        ("block elements", "symbol"),
        ("miscellaneous symbols", "symbol"),
        ("miscellaneous symbols supplement", "symbol"),
        ("symbols for legacy computing", "symbol"),
        ("symbols for legacy computing supplement", "symbol"),
        ("cjk strokes", "cjk-misc"),
        ("cjk symbols and punctuation", "cjk-misc"),
        ("halfwidth and fullwidth forms", "cjk-misc"),
        ("yijing hexagram symbols", "cjk-misc"),
        ("common indic number forms", "north-indic-number"),
    ])
}

fn generate_emoji_zwj(emoji_zwj_sequences: &Path, emoji_sequences: &Path) -> String {
    let mut sequences: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for path in [emoji_zwj_sequences, emoji_sequences] {
        for line in fs::read_to_string(path)
            .unwrap_or_else(|err| panic!("read {}: {err}", path.display()))
            .lines()
        {
            if !starts_with_hex(line)
                || !(line.contains("; RGI_Emoji_ZWJ_Sequence")
                    || line.contains("; RGI_Emoji_Modifier_Sequence"))
            {
                continue;
            }
            let raw = line.split(';').next().unwrap_or_default().trim();
            let parts = raw.split_whitespace().collect::<Vec<_>>();
            if parts.is_empty() {
                continue;
            }
            let base = parts[0].to_string();
            let seq = parts
                .iter()
                .map(|part| format!("\\N{{U+{part}}}"))
                .collect::<String>();
            sequences
                .entry(base)
                .or_default()
                .push(format!("\"{seq}\""));
        }
    }

    let trigger_codepoints = [
        "261D", "26F9", "270C", "270D", "2764", "1F3CB", "1F3CC", "1F3F3", "1F3F4", "1F441",
        "1F574", "1F575", "1F590", "20E3",
    ];

    let mut out = String::new();
    out.push_str(
        ";;; emoji-zwj.el --- emoji zwj character composition table  -*- lexical-binding:t -*-\n",
    );
    out.push_str(";;; Automatically generated from admin/unidata/emoji-{zwj-,}sequences.txt\n");
    out.push_str("(eval-when-compile (require 'regexp-opt))\n");
    out.push_str("(setq auto-composition-emoji-eligible-codepoints\n");
    out.push_str("'(\n");
    for codepoint in trigger_codepoints {
        let _ = writeln!(out, "?\\N{{U+{codepoint}}}");
    }
    out.push_str("))\n");
    out.push_str("(dolist (elt (eval-when-compile `(\n");
    for (base, seqs) in &sequences {
        let _ = writeln!(out, "(#x{base} .");
        out.push_str(",(regexp-opt\n");
        out.push_str("'(\n");
        for seq in seqs {
            let _ = writeln!(out, "{seq}");
        }
        let _ = writeln!(out, "\"\\N{{U+{base}}}\\N{{U+FE0E}}\"");
        let _ = writeln!(out, "\"\\N{{U+{base}}}\\N{{U+FE0F}}\"");
        out.push_str(")))\n");
    }
    out.push_str(")))\n");
    out.push_str("  (set-char-table-range composition-function-table\n");
    out.push_str("                        (car elt)\n");
    out.push_str(
        "                        (nconc (char-table-range composition-function-table (car elt))\n",
    );
    out.push_str("                               (list (vector (cdr elt)\n");
    out.push_str("                                             0\n");
    out.push_str(
        "                                             #'compose-gstring-for-graphic)))))\n",
    );
    out.push('\n');
    out.push_str(";; The following two blocks are derived by hand from emoji-sequences.txt\n");
    out.push_str(
        ";; FIXME: add support for Emoji_Keycap_Sequence once we learn how to respect FE0F/VS-16\n",
    );
    out.push_str(";; for ASCII characters.\n");
    out.push('\n');
    out.push_str(";; Flags\n");
    out.push_str("(set-char-table-range composition-function-table\n");
    out.push_str("                      '(#x1F1E6 . #x1F1FF)\n");
    out.push_str("                      (nconc (char-table-range composition-function-table '(#x1F1E6 . #x1F1FF))\n");
    out.push_str("                             (list (vector \"[\\\\U0001F1E6-\\\\U0001F1FF][\\\\U0001F1E6-\\\\U0001F1FF]\"\n");
    out.push_str("                                           0\n");
    out.push_str("                                           #'compose-gstring-for-graphic))))\n");
    out.push('\n');
    out.push_str(";; UK Flags\n");
    out.push_str("(set-char-table-range composition-function-table\n");
    out.push_str("                      #x1F3F4\n");
    out.push_str(
        "                      (nconc (char-table-range composition-function-table #x1F3F4)\n",
    );
    out.push_str("                             (list (vector \"\\\\U0001F3F4\\\\U000E0067\\\\U000E0062\\\\(?:\\\\U000E0065\\\\U000E006E\\\\U000E0067\\\\|\\\\U000E0073\\\\U000E0063\\\\U000E0074\\\\|\\\\U000E0077\\\\U000E006C\\\\U000E0073\\\\)\\\\U000E007F\"\n");
    out.push_str("                                           0\n");
    out.push_str("                                           #'compose-gstring-for-graphic))))\n");
    out.push('\n');
    out.push_str("(provide 'emoji-zwj)\n");
    out
}

fn parse_hex(value: &str) -> u32 {
    u32::from_str_radix(value, 16).unwrap_or_else(|err| panic!("invalid hex {value}: {err}"))
}

fn starts_with_hex(line: &str) -> bool {
    line.as_bytes()
        .first()
        .is_some_and(|b| (*b as char).is_ascii_hexdigit())
}

fn contains_any(haystack: &str, needles: &[&str]) -> bool {
    needles.iter().any(|needle| haystack.contains(needle))
}

fn earliest_match(haystack: &str, needles: &[&str]) -> Option<usize> {
    needles
        .iter()
        .filter_map(|needle| haystack.find(needle))
        .min()
}
