#!/usr/bin/env python3
"""Extract GNU Emacs DEFVAR doc: text into a Rust source file.

Walks every `.c` file in GNU Emacs's `src/` directory looking for
DEFVAR declarations of the form:

    DEFVAR_LISP ("name", Vsymbol,
                 doc: /* DOCSTRING TEXT
    POSSIBLY MULTI-LINE */);

    DEFVAR_INT ("name", c_var,
                doc: /* DOCSTRING */);

    DEFVAR_BOOL ("name", c_var,
                 doc: /* DOCSTRING */);

    DEFVAR_KBOARD ("name", kboard_field,
                   doc: /* DOCSTRING */);

For each match, emits a `(name, doc)` tuple to a Rust file:

    pub(crate) static GNU_VAR_DOCS: &[(&str, &str)] = &[
        ("name", "DOCSTRING TEXT\\nPOSSIBLY MULTI-LINE"),
        ...
    ];

Output is sorted alphabetically by name. Unlike DEFUN docs, DEFVAR
docs do NOT get a `(fn ARGS)` suffix appended.

Usage:
    scripts/extract_gnu_defvar_docs.py \\
        --gnu-src /path/to/emacs-mirror/emacs/src \\
        --output  neovm-core/src/emacs_core/var_docs/gnu_table.rs
"""

import argparse
import os
import re
import sys
from pathlib import Path


# Match the start of a DEFVAR_* declaration. We capture the name
# (group 1) and the variant (group 2) for diagnostic purposes.
# The DEFVAR may span multiple lines; we just need the name and a
# pointer to the position right after the C-variable identifier.
DEFVAR_HEAD = re.compile(
    r'\bDEFVAR_(LISP|BOOL|INT|KBOARD|LISP_NOPRO|PER_BUFFER)\s*\(\s*"([^"]+)"\s*,'
    r'\s*[A-Za-z_][A-Za-z0-9_]*'   # C variable name
    r'(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*'  # optional extra args (DEFVAR_PER_BUFFER)
    r'\s*,',
)


def find_doc_block(text: str, start: int) -> tuple[str | None, int]:
    """Find the `doc: /* ... */)` block starting at or after `start`.
    Returns (doc_text, end_offset) or (None, start) on failure.
    """
    doc_marker = text.find("doc: /*", start)
    if doc_marker == -1:
        return None, start
    # Bound the search: don't cross another DEFVAR boundary.
    next_defvar = text.find("DEFVAR_", start + 1)
    if next_defvar != -1 and next_defvar < doc_marker:
        return None, start
    body_start = doc_marker + len("doc: /*")
    body_end = text.find("*/", body_start)
    if body_end == -1:
        return None, start
    body = text[body_start:body_end]
    # Strip leading/trailing single space (matches make-docfile.c).
    if body.startswith(" "):
        body = body[1:]
    if body.endswith(" "):
        body = body[:-1]
    return body.rstrip(), body_end + 2


def extract_defvars(src: str) -> list[tuple[str, str]]:
    """Extract `(name, doc)` pairs from a single C source file."""
    results = []
    pos = 0
    while True:
        m = DEFVAR_HEAD.search(src, pos)
        if not m:
            break
        name = m.group(2)
        doc, doc_end = find_doc_block(src, m.end())
        if doc is not None:
            results.append((name, doc))
            pos = doc_end
        else:
            pos = m.end()
    return results


def rust_string_literal(s: str) -> str:
    """Format a Rust string literal that handles `\\`, `"`, and newlines.
    Uses raw string syntax `r#"..."#` when possible to preserve grave
    quotes verbatim, falling back to escaped form if the raw delimiter
    appears in the body."""
    if '"#' not in s and not any(ord(c) < 32 and c != "\n" and c != "\t" for c in s):
        for hashes in ["#", "##", "###"]:
            if f'"{hashes}' not in s:
                return f'r{hashes}"{s}"{hashes}'
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def emit_rust(entries: list[tuple[str, str]], output: Path) -> None:
    entries_sorted = sorted(entries, key=lambda kv: kv[0])
    lines = [
        "// AUTO-GENERATED by scripts/extract_gnu_defvar_docs.py — DO NOT EDIT.",
        "//",
        "// Source: GNU Emacs `src/*.c` DEFVAR_{LISP,INT,BOOL,KBOARD,...} doc: text.",
        "// Re-run the extractor against an updated GNU mirror to refresh.",
        "//",
        "// Each entry is `(name, raw_grave_quoted_doc)' lifted verbatim",
        "// from the corresponding DEFVAR block. Strings preserve GNU's",
        "// grave-quote convention so that `substitute-command-keys' can",
        "// convert them per the user's `text-quoting-style' at display",
        "// time.",
        "//",
        "// Variables don't have an `(fn ARGS)' suffix -- only DEFUNs do.",
        "",
        "pub(crate) static GNU_VAR_DOCS: &[(&str, &str)] = &[",
    ]
    for name, doc in entries_sorted:
        name_lit = rust_string_literal(name)
        doc_lit = rust_string_literal(doc)
        lines.append(f"    ({name_lit}, {doc_lit}),")
    lines.append("];")
    lines.append("")
    output.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gnu-src", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    if not args.gnu_src.is_dir():
        print(f"error: {args.gnu_src} is not a directory", file=sys.stderr)
        return 1

    all_entries: list[tuple[str, str]] = []
    seen_names: set[str] = set()
    for c_file in sorted(args.gnu_src.glob("*.c")):
        try:
            src = c_file.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            print(f"warning: cannot read {c_file}: {e}", file=sys.stderr)
            continue
        entries = extract_defvars(src)
        for name, doc in entries:
            if name in seen_names:
                print(
                    f"note: duplicate DEFVAR '{name}' in {c_file.name}, "
                    f"keeping the earlier definition",
                    file=sys.stderr,
                )
                continue
            seen_names.add(name)
            all_entries.append((name, doc))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    emit_rust(all_entries, args.output)
    print(
        f"extracted {len(all_entries)} DEFVAR docs from "
        f"{args.gnu_src} -> {args.output}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
